# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

   config.vm.box = "scotch/box"
   config.vm.network "private_network", ip: "192.168.33.10"
   config.vm.hostname = "devbox"
    config.vm.synced_folder ".", "/var/www", :nfs => { :mount_options => ["dmode=777","fmode=666"] }


    config.vm.provision "shell", inline: <<-SHELL
    	sudo apt-get update
        sudo apt-get upgrade -y
        sudo apt-get install php5-xdebug -y
    	sudo service apache2 restart
## Mas Proyectos?, crealos en este array, formato <dominio>:<carpeta-publica>
DOMAINS=('proyectos.local:public' 'test.local:web')

## Loop through all sites
for elt in "${DOMAINS[@]}"; do    
    
    IFS=: read DOMAIN DIRWEB <<< $elt
    echo "$DOMAIN*$DIRWEB"

            echo "Creando un directorio publico para $DOMAIN. Directorio: $DIRWEB"
            mkdir -p /var/www/$DOMAIN/$DIRWEB

            echo "Creando configuracion vhost para $DOMAIN"
            sudo cp /etc/apache2/sites-available/scotchbox.local.conf /etc/apache2/sites-available/$DOMAIN.conf

            echo "Actualizando vhost para $DOMAIN"
            sudo sed -i s,scotchbox.local,$DOMAIN,g /etc/apache2/sites-available/$DOMAIN.conf
            sudo sed -i s,/var/www/$DIRWEB,/var/www/$DOMAIN/$DIRWEB,g /etc/apache2/sites-available/$DOMAIN.conf

            echo "Enabling $DOMAIN"
            sudo a2ensite $DOMAIN.conf

            echo "Restart Apache ..."
            sudo service apache2 restart
	    
	done

    SHELL

end
